abomasnow:
- '4'
abra:
- '1'
absol:
- '3'
accelgor:
- '5'
aegislash:
- '6'
aerodactyl:
- '1'
aggron:
- '3'
aipom:
- '2'
alakazam:
- '1'
alcremie:
- '8'
alomomola:
- '5'
altaria:
- '3'
amaura:
- '6'
ambipom:
- '4'
amoonguss:
- '5'
ampharos:
- '2'
annihilape:
- '9'
anorith:
- '3'
appletun:
- '8'
applin:
- '8'
araquanid:
- '7'
arbok:
- '1'
arboliva:
- '9'
arcanine:
- '1'
arceus:
- '4'
archaludon:
- '9'
archen:
- '5'
archeops:
- '5'
arctibax:
- '9'
arctovish:
- '8'
arctozolt:
- '8'
ariados:
- '2'
armaldo:
- '3'
armarouge:
- '9'
aromatisse:
- '6'
aron:
- '3'
arrokuda:
- '8'
articuno:
- '1'
audino:
- '5'
aurorus:
- '6'
avalugg:
- '6'
axew:
- '5'
azelf:
- '4'
azumarill:
- '2'
azurill:
- '3'
bagon:
- '3'
baltoy:
- '3'
banette:
- '3'
barbaracle:
- '6'
barboach:
- '3'
barraskewda:
- '8'
basculegion:
- '8'
basculin:
- '5'
bastiodon:
- '4'
baxcalibur:
- '9'
bayleef:
- '2'
beartic:
- '5'
beautifly:
- '3'
beedrill:
- '1'
beheeyem:
- '5'
beldum:
- '3'
bellibolt:
- '9'
bellossom:
- '2'
bellsprout:
- '1'
bergmite:
- '6'
bewear:
- '7'
bibarel:
- '4'
bidoof:
- '4'
binacle:
- '6'
bisharp:
- '5'
blacephalon:
- '7'
blastoise:
- '1'
blaziken:
- '3'
blipbug:
- '8'
blissey:
- '2'
blitzle:
- '5'
boldore:
- '5'
boltund:
- '8'
bombirdier:
- '9'
bonsly:
- '4'
bouffalant:
- '5'
bounsweet:
- '7'
braixen:
- '6'
brambleghast:
- '9'
bramblin:
- '9'
braviary:
- '5'
breloom:
- '3'
brionne:
- '7'
bronzong:
- '4'
bronzor:
- '4'
brute-bonnet:
- '9'
bruxish:
- '7'
budew:
- '4'
buizel:
- '4'
bulbasaur:
- '1'
buneary:
- '4'
bunnelby:
- '6'
burmy:
- '4'
butterfree:
- '1'
buzzwole:
- '7'
cacnea:
- '3'
cacturne:
- '3'
calyrex:
- '8'
camerupt:
- '3'
capsakid:
- '9'
carbink:
- '6'
carkol:
- '8'
carnivine:
- '4'
carracosta:
- '5'
carvanha:
- '3'
cascoon:
- '3'
castform:
- '3'
caterpie:
- '1'
celebi:
- '2'
celesteela:
- '7'
centiskorch:
- '8'
ceruledge:
- '9'
cetitan:
- '9'
cetoddle:
- '9'
chandelure:
- '5'
chansey:
- '1'
charcadet:
- '9'
charizard:
- '1'
charjabug:
- '7'
charmander:
- '1'
charmeleon:
- '1'
chatot:
- '4'
cherrim:
- '4'
cherubi:
- '4'
chesnaught:
- '6'
chespin:
- '6'
chewtle:
- '8'
chi-yu:
- '9'
chien-pao:
- '9'
chikorita:
- '2'
chimchar:
- '4'
chimecho:
- '3'
chinchou:
- '2'
chingling:
- '4'
cinccino:
- '5'
cinderace:
- '8'
clamperl:
- '3'
clauncher:
- '6'
clawitzer:
- '6'
claydol:
- '3'
clefable:
- '1'
clefairy:
- '1'
cleffa:
- '2'
clobbopus:
- '8'
clodsire:
- '9'
cloyster:
- '1'
coalossal:
- '8'
cobalion:
- '5'
cofagrigus:
- '5'
combee:
- '4'
combusken:
- '3'
comfey:
- '7'
conkeldurr:
- '5'
copperajah:
- '8'
corphish:
- '3'
corsola:
- '2'
corviknight:
- '8'
corvisquire:
- '8'
cosmoem:
- '7'
cosmog:
- '7'
cottonee:
- '5'
crabominable:
- '7'
crabrawler:
- '7'
cradily:
- '3'
cramorant:
- '8'
cranidos:
- '4'
crawdaunt:
- '3'
cresselia:
- '4'
croagunk:
- '4'
crobat:
- '2'
crocalor:
- '9'
croconaw:
- '2'
crustle:
- '5'
cryogonal:
- '5'
cubchoo:
- '5'
cubone:
- '1'
cufant:
- '8'
cursola:
- '8'
cutiefly:
- '7'
cyclizar:
- '9'
cyndaquil:
- '2'
dachsbun:
- '9'
darkrai:
- '4'
darmanitan:
- '5'
dartrix:
- '7'
darumaka:
- '5'
decidueye:
- '7'
dedenne:
- '6'
deerling:
- '5'
deino:
- '5'
delcatty:
- '3'
delibird:
- '2'
delphox:
- '6'
deoxys:
- '3'
dewgong:
- '1'
dewott:
- '5'
dewpider:
- '7'
dhelmise:
- '7'
dialga:
- '4'
diancie:
- '6'
diggersby:
- '6'
diglett:
- '1'
dipplin:
- '9'
ditto:
- '1'
dodrio:
- '1'
doduo:
- '1'
dolliv:
- '9'
dondozo:
- '9'
donphan:
- '2'
dottler:
- '8'
doublade:
- '6'
dracovish:
- '8'
dracozolt:
- '8'
dragalge:
- '6'
dragapult:
- '8'
dragonair:
- '1'
dragonite:
- '1'
drakloak:
- '8'
drampa:
- '7'
drapion:
- '4'
dratini:
- '1'
drednaw:
- '8'
dreepy:
- '8'
drifblim:
- '4'
drifloon:
- '4'
drilbur:
- '5'
drizzile:
- '8'
drowzee:
- '1'
druddigon:
- '5'
dubwool:
- '8'
ducklett:
- '5'
dudunsparce:
- '9'
dugtrio:
- '1'
dunsparce:
- '2'
duosion:
- '5'
duraludon:
- '8'
durant:
- '5'
dusclops:
- '3'
dusknoir:
- '4'
duskull:
- '3'
dustox:
- '3'
dwebble:
- '5'
eelektrik:
- '5'
eelektross:
- '5'
eevee:
- '1'
eiscue:
- '8'
ekans:
- '1'
eldegoss:
- '8'
electabuzz:
- '1'
electivire:
- '4'
electrike:
- '3'
electrode:
- '1'
elekid:
- '2'
elgyem:
- '5'
emboar:
- '5'
emolga:
- '5'
empoleon:
- '4'
enamorus:
- '8'
entei:
- '2'
escavalier:
- '5'
espathra:
- '9'
espeon:
- '2'
espurr:
- '6'
eternatus:
- '8'
excadrill:
- '5'
exeggcute:
- '1'
exeggutor:
- '1'
exploud:
- '3'
falinks:
- '8'
farfetchd:
- '1'
farigiraf:
- '9'
fearow:
- '1'
feebas:
- '3'
fennekin:
- '6'
feraligatr:
- '2'
ferroseed:
- '5'
ferrothorn:
- '5'
fezandipiti:
- '9'
fidough:
- '9'
finizen:
- '9'
finneon:
- '4'
flaaffy:
- '2'
flabebe:
- '6'
flamigo:
- '9'
flapple:
- '8'
flareon:
- '1'
fletchinder:
- '6'
fletchling:
- '6'
flittle:
- '9'
floatzel:
- '4'
floette:
- '6'
floragato:
- '9'
florges:
- '6'
flutter-mane:
- '9'
flygon:
- '3'
fomantis:
- '7'
foongus:
- '5'
forretress:
- '2'
fraxure:
- '5'
frigibax:
- '9'
frillish:
- '5'
froakie:
- '6'
frogadier:
- '6'
froslass:
- '4'
frosmoth:
- '8'
fuecoco:
- '9'
furfrou:
- '6'
furret:
- '2'
gabite:
- '4'
gallade:
- '4'
galvantula:
- '5'
garbodor:
- '5'
garchomp:
- '4'
gardevoir:
- '3'
garganacl:
- '9'
gastly:
- '1'
gastrodon:
- '4'
genesect:
- '5'
gengar:
- '1'
geodude:
- '1'
gholdengo:
- '9'
gible:
- '4'
gigalith:
- '5'
gimmighoul:
- '9'
girafarig:
- '2'
giratina:
- '4'
glaceon:
- '4'
glalie:
- '3'
glameow:
- '4'
glastrier:
- '8'
gligar:
- '2'
glimmet:
- '9'
glimmora:
- '9'
gliscor:
- '4'
gloom:
- '1'
gogoat:
- '6'
golbat:
- '1'
goldeen:
- '1'
golduck:
- '1'
golem:
- '1'
golett:
- '5'
golisopod:
- '7'
golurk:
- '5'
goodra:
- '6'
goomy:
- '6'
gorebyss:
- '3'
gossifleur:
- '8'
gothita:
- '5'
gothitelle:
- '5'
gothorita:
- '5'
gouging-fire:
- '9'
gourgeist:
- '6'
grafaiai:
- '9'
granbull:
- '2'
grapploct:
- '8'
graveler:
- '1'
great-tusk:
- '9'
greavard:
- '9'
greedent:
- '8'
greninja:
- '6'
grimer:
- '1'
grimmsnarl:
- '8'
grookey:
- '8'
grotle:
- '4'
groudon:
- '3'
grovyle:
- '3'
growlithe:
- '1'
grubbin:
- '7'
grumpig:
- '3'
gulpin:
- '3'
gumshoos:
- '7'
gurdurr:
- '5'
guzzlord:
- '7'
gyarados:
- '1'
hakamo-o:
- '7'
happiny:
- '4'
hariyama:
- '3'
hatenna:
- '8'
hatterene:
- '8'
hattrem:
- '8'
haunter:
- '1'
hawlucha:
- '6'
haxorus:
- '5'
heatmor:
- '5'
heatran:
- '4'
heliolisk:
- '6'
helioptile:
- '6'
heracross:
- '2'
herdier:
- '5'
hippopotas:
- '4'
hippowdon:
- '4'
hitmonchan:
- '1'
hitmonlee:
- '1'
hitmontop:
- '2'
ho-oh:
- '2'
honchkrow:
- '4'
honedge:
- '6'
hoopa:
- '6'
hoothoot:
- '2'
hoppip:
- '2'
horsea:
- '1'
houndoom:
- '2'
houndour:
- '2'
houndstone:
- '9'
huntail:
- '3'
hydrapple:
- '9'
hydreigon:
- '5'
hypno:
- '1'
igglybuff:
- '2'
illumise:
- '3'
impidimp:
- '8'
incineroar:
- '7'
indeedee:
- '8'
infernape:
- '4'
inkay:
- '6'
inteleon:
- '8'
iron-boulder:
- '9'
iron-bundle:
- '9'
iron-crown:
- '9'
iron-hands:
- '9'
iron-jugulis:
- '9'
iron-leaves:
- '9'
iron-moth:
- '9'
iron-thorns:
- '9'
iron-treads:
- '9'
iron-valiant:
- '9'
ivysaur:
- '1'
jangmo-o:
- '7'
jellicent:
- '5'
jigglypuff:
- '1'
jirachi:
- '3'
jolteon:
- '1'
joltik:
- '5'
jumpluff:
- '2'
jynx:
- '1'
kabuto:
- '1'
kabutops:
- '1'
kadabra:
- '1'
kakuna:
- '1'
kangaskhan:
- '1'
karrablast:
- '5'
kartana:
- '7'
kecleon:
- '3'
keldeo:
- '5'
kilowattrel:
- '9'
kingambit:
- '9'
kingdra:
- '2'
kingler:
- '1'
kirlia:
- '3'
klang:
- '5'
klawf:
- '9'
kleavor:
- '8'
klefki:
- '6'
klink:
- '5'
klinklang:
- '5'
koffing:
- '1'
komala:
- '7'
kommo-o:
- '7'
koraidon:
- '9'
krabby:
- '1'
kricketot:
- '4'
kricketune:
- '4'
krokorok:
- '5'
krookodile:
- '5'
kubfu:
- '8'
kyogre:
- '3'
kyurem:
- '5'
lairon:
- '3'
lampent:
- '5'
landorus:
- '5'
lanturn:
- '2'
lapras:
- '1'
larvesta:
- '5'
larvitar:
- '2'
latias:
- '3'
latios:
- '3'
leafeon:
- '4'
leavanny:
- '5'
lechonk:
- '9'
ledian:
- '2'
ledyba:
- '2'
lickilicky:
- '4'
lickitung:
- '1'
liepard:
- '5'
lileep:
- '3'
lilligant:
- '5'
lillipup:
- '5'
linoone:
- '3'
litleo:
- '6'
litten:
- '7'
litwick:
- '5'
lokix:
- '9'
lombre:
- '3'
lopunny:
- '4'
lotad:
- '3'
loudred:
- '3'
lucario:
- '4'
ludicolo:
- '3'
lugia:
- '2'
lumineon:
- '4'
lunala:
- '7'
lunatone:
- '3'
lurantis:
- '7'
luvdisc:
- '3'
luxio:
- '4'
luxray:
- '4'
lycanroc:
- '7'
mabosstiff:
- '9'
machamp:
- '1'
machoke:
- '1'
machop:
- '1'
magby:
- '2'
magcargo:
- '2'
magearna:
- '7'
magikarp:
- '1'
magmar:
- '1'
magmortar:
- '4'
magnemite:
- '1'
magneton:
- '1'
magnezone:
- '4'
makuhita:
- '3'
malamar:
- '6'
mamoswine:
- '4'
manaphy:
- '4'
mandibuzz:
- '5'
manectric:
- '3'
mankey:
- '1'
mantine:
- '2'
mantyke:
- '4'
maractus:
- '5'
mareanie:
- '7'
mareep:
- '2'
marill:
- '2'
marowak:
- '1'
marshadow:
- '7'
marshtomp:
- '3'
maschiff:
- '9'
masquerain:
- '3'
maushold:
- '9'
mawile:
- '3'
medicham:
- '3'
meditite:
- '3'
meganium:
- '2'
melmetal:
- '7'
meloetta:
- '5'
meltan:
- '7'
meowscarada:
- '9'
meowstic:
- '6'
meowth:
- '1'
mesprit:
- '4'
metagross:
- '3'
metang:
- '3'
metapod:
- '1'
mew:
- '1'
mewtwo:
- '1'
mienfoo:
- '5'
mienshao:
- '5'
mightyena:
- '3'
milcery:
- '8'
milotic:
- '3'
miltank:
- '2'
mime-jr:
- '4'
mimikyu:
- '7'
minccino:
- '5'
minior:
- '7'
minun:
- '3'
miraidon:
- '9'
misdreavus:
- '2'
mismagius:
- '4'
moltres:
- '1'
monferno:
- '4'
morelull:
- '7'
morgrem:
- '8'
morpeko:
- '8'
mothim:
- '4'
mr-mime:
- '1'
mr-rime:
- '8'
mudbray:
- '7'
mudkip:
- '3'
mudsdale:
- '7'
muk:
- '1'
munchlax:
- '4'
munkidori:
- '9'
munna:
- '5'
murkrow:
- '2'
musharna:
- '5'
nacli:
- '9'
naclstack:
- '9'
naganadel:
- '7'
natu:
- '2'
necrozma:
- '7'
nickit:
- '8'
nidoking:
- '1'
nidoqueen:
- '1'
nidoran-f:
- '1'
nidoran-m:
- '1'
nidorina:
- '1'
nidorino:
- '1'
nihilego:
- '7'
nincada:
- '3'
ninetales:
- '1'
ninjask:
- '3'
noctowl:
- '2'
noibat:
- '6'
noivern:
- '6'
nosepass:
- '3'
numel:
- '3'
nuzleaf:
- '3'
nymble:
- '9'
obstagoon:
- '8'
octillery:
- '2'
oddish:
- '1'
ogerpon:
- '9'
oinkologne:
- '9'
okidogi:
- '9'
omanyte:
- '1'
omastar:
- '1'
onix:
- '1'
oranguru:
- '7'
orbeetle:
- '8'
oricorio:
- '7'
orthworm:
- '9'
oshawott:
- '5'
overqwil:
- '8'
pachirisu:
- '4'
palafin:
- '9'
palkia:
- '4'
palossand:
- '7'
palpitoad:
- '5'
pancham:
- '6'
pangoro:
- '6'
panpour:
- '5'
pansage:
- '5'
pansear:
- '5'
paras:
- '1'
parasect:
- '1'
passimian:
- '7'
patrat:
- '5'
pawmi:
- '9'
pawmo:
- '9'
pawmot:
- '9'
pawniard:
- '5'
pecharunt:
- '9'
pelipper:
- '3'
perrserker:
- '8'
persian:
- '1'
petilil:
- '5'
phanpy:
- '2'
phantump:
- '6'
pheromosa:
- '7'
phione:
- '4'
pichu:
- '2'
pidgeot:
- '1'
pidgeotto:
- '1'
pidgey:
- '1'
pidove:
- '5'
pignite:
- '5'
pikachu:
- '1'
pikipek:
- '7'
piloswine:
- '2'
pincurchin:
- '8'
pineco:
- '2'
pinsir:
- '1'
piplup:
- '4'
plusle:
- '3'
poipole:
- '7'
politoed:
- '2'
poliwag:
- '1'
poliwhirl:
- '1'
poliwrath:
- '1'
poltchageist:
- '9'
polteageist:
- '8'
ponyta:
- '1'
poochyena:
- '3'
popplio:
- '7'
porygon:
- '1'
porygon-z:
- '4'
porygon2:
- '2'
primarina:
- '7'
primeape:
- '1'
prinplup:
- '4'
probopass:
- '4'
psyduck:
- '1'
pumpkaboo:
- '6'
pupitar:
- '2'
purrloin:
- '5'
purugly:
- '4'
pyroar:
- '6'
pyukumuku:
- '7'
quagsire:
- '2'
quaquaval:
- '9'
quaxly:
- '9'
quaxwell:
- '9'
quilava:
- '2'
quilladin:
- '6'
qwilfish:
- '2'
raboot:
- '8'
rabsca:
- '9'
raging-bolt:
- '9'
raichu:
- '1'
raikou:
- '2'
ralts:
- '3'
rampardos:
- '4'
rapidash:
- '1'
raticate:
- '1'
rattata:
- '1'
rayquaza:
- '3'
regice:
- '3'
regidrago:
- '8'
regieleki:
- '8'
regigigas:
- '4'
regirock:
- '3'
registeel:
- '3'
relicanth:
- '3'
rellor:
- '9'
remoraid:
- '2'
reshiram:
- '5'
reuniclus:
- '5'
revavroom:
- '9'
rhydon:
- '1'
rhyhorn:
- '1'
rhyperior:
- '4'
ribombee:
- '7'
rillaboom:
- '8'
riolu:
- '4'
roaring-moon:
- '9'
rockruff:
- '7'
roggenrola:
- '5'
rolycoly:
- '8'
rookidee:
- '8'
roselia:
- '3'
roserade:
- '4'
rotom:
- '4'
rowlet:
- '7'
rufflet:
- '5'
runerigus:
- '8'
sableye:
- '3'
salamence:
- '3'
salandit:
- '7'
salazzle:
- '7'
samurott:
- '5'
sandaconda:
- '8'
sandile:
- '5'
sandshrew:
- '1'
sandslash:
- '1'
sandy-shocks:
- '9'
sandygast:
- '7'
sawk:
- '5'
sawsbuck:
- '5'
scatterbug:
- '6'
sceptile:
- '3'
scizor:
- '2'
scolipede:
- '5'
scorbunny:
- '8'
scovillain:
- '9'
scrafty:
- '5'
scraggy:
- '5'
scream-tail:
- '9'
scyther:
- '1'
seadra:
- '1'
seaking:
- '1'
sealeo:
- '3'
seedot:
- '3'
seel:
- '1'
seismitoad:
- '5'
sentret:
- '2'
serperior:
- '5'
servine:
- '5'
seviper:
- '3'
sewaddle:
- '5'
sharpedo:
- '3'
shaymin:
- '4'
shedinja:
- '3'
shelgon:
- '3'
shellder:
- '1'
shellos:
- '4'
shelmet:
- '5'
shieldon:
- '4'
shiftry:
- '3'
shiinotic:
- '7'
shinx:
- '4'
shroodle:
- '9'
shroomish:
- '3'
shuckle:
- '2'
shuppet:
- '3'
sigilyph:
- '5'
silcoon:
- '3'
silicobra:
- '8'
silvally:
- '7'
simipour:
- '5'
simisage:
- '5'
simisear:
- '5'
sinistcha:
- '9'
sinistea:
- '8'
sirfetchd:
- '8'
sizzlipede:
- '8'
skarmory:
- '2'
skeledirge:
- '9'
skiddo:
- '6'
skiploom:
- '2'
skitty:
- '3'
skorupi:
- '4'
skrelp:
- '6'
skuntank:
- '4'
skwovet:
- '8'
slaking:
- '3'
slakoth:
- '3'
sliggoo:
- '6'
slither-wing:
- '9'
slowbro:
- '1'
slowking:
- '2'
slowpoke:
- '1'
slugma:
- '2'
slurpuff:
- '6'
smeargle:
- '2'
smoliv:
- '9'
smoochum:
- '2'
sneasel:
- '2'
sneasler:
- '8'
snivy:
- '5'
snom:
- '8'
snorlax:
- '1'
snorunt:
- '3'
snover:
- '4'
snubbull:
- '2'
sobble:
- '8'
solgaleo:
- '7'
solosis:
- '5'
solrock:
- '3'
spearow:
- '1'
spectrier:
- '8'
spewpa:
- '6'
spheal:
- '3'
spidops:
- '9'
spinarak:
- '2'
spinda:
- '3'
spiritomb:
- '4'
spoink:
- '3'
sprigatito:
- '9'
spritzee:
- '6'
squawkabilly:
- '9'
squirtle:
- '1'
stakataka:
- '7'
stantler:
- '2'
staraptor:
- '4'
staravia:
- '4'
starly:
- '4'
starmie:
- '1'
staryu:
- '1'
steelix:
- '2'
steenee:
- '7'
stonjourner:
- '8'
stoutland:
- '5'
stufful:
- '7'
stunfisk:
- '5'
stunky:
- '4'
sudowoodo:
- '2'
suicune:
- '2'
sunflora:
- '2'
sunkern:
- '2'
surskit:
- '3'
swablu:
- '3'
swadloon:
- '5'
swalot:
- '3'
swampert:
- '3'
swanna:
- '5'
swellow:
- '3'
swinub:
- '2'
swirlix:
- '6'
swoobat:
- '5'
sylveon:
- '6'
tadbulb:
- '9'
taillow:
- '3'
talonflame:
- '6'
tandemaus:
- '9'
tangela:
- '1'
tangrowth:
- '4'
tapu-bulu:
- '7'
tapu-fini:
- '7'
tapu-koko:
- '7'
tapu-lele:
- '7'
tarountula:
- '9'
tatsugiri:
- '9'
tauros:
- '1'
teddiursa:
- '2'
tentacool:
- '1'
tentacruel:
- '1'
tepig:
- '5'
terapagos:
- '9'
terrakion:
- '5'
thievul:
- '8'
throh:
- '5'
thundurus:
- '5'
thwackey:
- '8'
timburr:
- '5'
ting-lu:
- '9'
tinkatink:
- '9'
tinkaton:
- '9'
tinkatuff:
- '9'
tirtouga:
- '5'
toedscool:
- '9'
toedscruel:
- '9'
togedemaru:
- '7'
togekiss:
- '4'
togepi:
- '2'
togetic:
- '2'
torchic:
- '3'
torkoal:
- '3'
tornadus:
- '5'
torracat:
- '7'
torterra:
- '4'
totodile:
- '2'
toucannon:
- '7'
toxapex:
- '7'
toxel:
- '8'
toxicroak:
- '4'
toxtricity:
- '8'
tranquill:
- '5'
trapinch:
- '3'
treecko:
- '3'
trevenant:
- '6'
tropius:
- '3'
trubbish:
- '5'
trumbeak:
- '7'
tsareena:
- '7'
turtonator:
- '7'
turtwig:
- '4'
tympole:
- '5'
tynamo:
- '5'
type-null:
- '7'
typhlosion:
- '2'
tyranitar:
- '2'
tyrantrum:
- '6'
tyrogue:
- '2'
tyrunt:
- '6'
umbreon:
- '2'
unfezant:
- '5'
unown:
- '2'
ursaluna:
- '8'
ursaring:
- '2'
urshifu:
- '8'
uxie:
- '4'
vanillish:
- '5'
vanillite:
- '5'
vanilluxe:
- '5'
vaporeon:
- '1'
varoom:
- '9'
veluza:
- '9'
venipede:
- '5'
venomoth:
- '1'
venonat:
- '1'
venusaur:
- '1'
vespiquen:
- '4'
vibrava:
- '3'
victini:
- '5'
victreebel:
- '1'
vigoroth:
- '3'
vikavolt:
- '7'
vileplume:
- '1'
virizion:
- '5'
vivillon:
- '6'
volbeat:
- '3'
volcanion:
- '6'
volcarona:
- '5'
voltorb:
- '1'
vullaby:
- '5'
vulpix:
- '1'
wailmer:
- '3'
wailord:
- '3'
walking-wake:
- '9'
walrein:
- '3'
wartortle:
- '1'
watchog:
- '5'
wattrel:
- '9'
weavile:
- '4'
weedle:
- '1'
weepinbell:
- '1'
weezing:
- '1'
whimsicott:
- '5'
whirlipede:
- '5'
whiscash:
- '3'
whismur:
- '3'
wigglytuff:
- '1'
wiglett:
- '9'
wimpod:
- '7'
wingull:
- '3'
wishiwashi:
- '7'
wo-chien:
- '9'
wobbuffet:
- '2'
woobat:
- '5'
wooloo:
- '8'
wooper:
- '2'
wormadam:
- '4'
wugtrio:
- '9'
wurmple:
- '3'
wynaut:
- '3'
wyrdeer:
- '8'
xatu:
- '2'
xerneas:
- '6'
xurkitree:
- '7'
yamask:
- '5'
yamper:
- '8'
yanma:
- '2'
yanmega:
- '4'
yungoos:
- '7'
yveltal:
- '6'
zacian:
- '8'
zamazenta:
- '8'
zangoose:
- '3'
zapdos:
- '1'
zarude:
- '8'
zebstrika:
- '5'
zekrom:
- '5'
zeraora:
- '7'
zigzagoon:
- '3'
zoroark:
- '5'
zorua:
- '5'
zubat:
- '1'
zweilous:
- '5'
zygarde:
- '6'
